steps:
  shellcheck:
    image: koalaman/shellcheck:stable
    commands:
      - shellcheck scripts/*.sh

  format-check:
    image: alpine:3.20
    commands:
      - echo "comprobar formato"

  syntax-check:
    image: bash:5.2
    commands:
      - bash -n scripts/*.sh

when:
  event: [push, pull_request]
