when:
  event: pull_request

steps:
  - name: shellcheck
    image: koalaman/shellcheck:stable
    commands:
      - find . -type f -name "*.sh" -exec shellcheck {} +

  - name: format-check
    image: mvdan/shfmt:v3.8.0
    commands:
      - shfmt -d .

  - name: syntax-check
    image: bash:5.2
    commands:
      - find . -type f -name "*.sh" -exec bash -n {} +
